# Generated by Django 4.1 on 2022-08-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('desc', models.TextField(max_length=1000000)),
                ('upload_on', models.CharField(max_length=50)),
                ('upload_by', models.CharField(max_length=100)),
                ('datefield', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
